services:
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7.2.1-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:15.4-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/app
    ports:
      - ${APP_PORT}:8080
    environment:
      ENV: local
      PORT: 8080
      REDIS_URL: redis:6379
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
  api:
    container_name: ${APP_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/api
    ports:
      - ${API_PORT}:8080
    environment:
      ENV: local
      PORT: 8080
      REDIS_URL: redis:6379
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
