name: lint yaml
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    paths:
      - "**/*.yaml"
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
      - name: Install yamlfmt
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install -t yamlfmt
      - name: Yaml format lint
        run: yamlfmt -lint
